src/objects/Dwolla_API_Log__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Stack_Trace_String__c</fullName>
        <label>Exception Stack Trace String</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Headers__c</fullName>
        <label>Headers</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsError__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsError</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <label>Status Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Dwolla API Log</label>
    <nameField>
        <displayFormat>DAL-{000000}</displayFormat>
        <label>Dwolla API Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dwolla API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Dwolla_API_Log_Level__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Log_All__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, all calls to the Dwolla API will be logged, regardless of success or error.</description>
        <label>Log All</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Log_Errors__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked, a Dwolla API Log record will be created when there is an error in a call to the Dwolla API</description>
        <inlineHelpText>If checked, a Dwolla API Log record will be created when there is an error in a call to the Dwolla API</inlineHelpText>
        <label>Log Errors</label>
        <type>Checkbox</type>
    </fields>
    <label>Dwolla API Log Level</label>
</CustomObject>

src/classes/ApexDwolla_API_Callout_Helper.cls
public class ApexDwolla_API_Callout_Helper {
    public static HttpRequest buildHttpRequest(String endpoint, String method, map<String,String> headers, String body){
        HttpRequest req = new HttpRequest();
        req.setEndpoint(endpoint);
        req.setMethod(method);
        for(String headerKey : headers.keySet()){
            req.setHeader(headerKey, headers.get(headerKey));
        }
        req.setBody(body);
        return req;
    }
    
    public static HttpResponse makeCallout(Http h, HTTPRequest req){
        Dwolla_API_Log_Level__c logLevel = Dwolla_API_Log_Level__c.getOrgDefaults();
        try{
            HttpResponse res = h.send(req);
            handleResponseStatus(res);
            if(logLevel.Log_All__c){
                generateApiLog(res);
            }
            return res;
        }
        catch(Exception e){
            if(logLevel.Log_Errors__c || logLevel.Log_All__c){
                //Create Dwolla_API_Log__c record with exception information
                String errorMsg = e.getTypeName() + ': ' + e.getMessage();
                String exceptionStackTrace = e.getStackTraceString();
                generateApiLog(errorMsg, exceptionStackTrace);
            }
            return null;
        }
    }
    
    public static void handleResponseStatus(HttpResponse res){
        Dwolla_API_Log_Level__c logLevel = Dwolla_API_Log_Level__c.getOrgDefaults();
        if(logLevel.Log_Errors__c || logLevel.Log_All__c){
            Integer statusCode = res.getStatusCode();
            String statusCodeStr = String.valueOf(statusCode);
            if(statusCode == 200){
                return;
            }
            else{
                //Create Dwolla_API_Log__c record with callout error information
                String errorMsg = statusCodeStr + ' ';
                JSONParser parser = JSON.createParser(res.getBody());
                ApexDwolla_API_Wrapper.CalloutError calloutError;
                if (parser.nextToken() == JSONToken.START_OBJECT) {
                    calloutError = (ApexDwolla_API_Wrapper.CalloutError)parser.readValueAs(ApexDwolla_API_Wrapper.CalloutError.class);
                }
                errorMsg += calloutError.code + ': ' + calloutError.message;
                generateApiLog(res, errorMsg);
            }
        }
    }
    
    public static void generateApiLog(HttpResponse res){
        Dwolla_API_Log__c apiLog = buildApiLog(res);
        insertApiLog(apiLog);
    }
    
    public static void generateApiLog(HttpResponse res, String errorMsg){
        Dwolla_API_Log__c apiLog = buildApiLog(res);
        apiLog.IsError__c = TRUE;
        apiLog.Error_Message__c = errorMsg;
        insertApiLog(apiLog);
    }
    
    public static void generateApiLog(String errorMsg, String exceptionStackTrace){
        Dwolla_API_Log__c apiLog = new Dwolla_API_Log__c(
            IsError__c = TRUE,
            Error_Message__c = errorMsg,
            Exception_Stack_Trace_String__c = exceptionStackTrace
        );
        insertApiLog(apiLog);
    }
    
    public static Dwolla_API_Log__c buildApiLog(HttpResponse res){
        String statusCode = String.valueOf(res.getStatusCode());
        String status = res.getStatus();
        String headers = '';
        for (String resKey : res.getHeaderKeys()){
            headers += resKey + ': ' + res.getHeader(resKey) + '\n';
        }
        
        //The goal of the following 2 lines is get the response body in a "pretty" (readable) format
        Map<String, Object> deserializedResponse = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
        String body = Json.serializePretty(deserializedResponse);
        
        return new Dwolla_API_Log__c(
            Status_Code__c = statusCode,
            Status__c = status,
            Headers__c = headers,
            Body__c = body
        );
    }
    
    public static void insertApiLog(Dwolla_API_Log__c apiLog){
        insert apiLog;
    }
}