src/objects/Dwolla_API_Connection__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to configure a connection to the Dwolla API. The API Wrapper uses org wide defaults only.</description>
    <fields>
        <fullName>API_Endpoint__c</fullName>
        <label>API Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>OAuth_Endpoint__c</fullName>
        <label>OAuth Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>OAuth_Key__c</fullName>
        <label>OAuth Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OAuth_Secret__c</fullName>
        <label>OAuth Secret</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Dwolla API Connection</label>
</CustomObject>

src/objects/Dwolla_API_Log_Level__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Log_All__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, all calls to the Dwolla API will be logged, regardless of success or error.</description>
        <label>Log All</label>
        <type>Checkbox</type>
    </fields>
    <label>Dwolla API Log Level</label>
</CustomObject>

src/classes/ApexDwolla_API_Test_Data.cls
public class ApexDwolla_API_Test_Data {
    public static void createApiConfigData() {
        Dwolla_API_Connection__c connection = Dwolla_API_Connection__c.getOrgDefaults();
        connection.API_Endpoint__c  = 'http://localhost';
        connection.OAuth_Endpoint__c = 'http://localhost';
        connection.OAuth_Key__c = '123';
        connection.OAuth_Secret__c = 'abc';
        insert connection;
        
        Dwolla_API_Log_Level__c logLevel = Dwolla_API_Log_Level__c.getOrgDefaults();
        logLevel.Log_All__c = true;
        insert logLevel;
    }
}